version: '3.3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: getchapull
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  spring:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"