app:
  datasource:
    jdbc-url: jdbc:postgresql://postgres:5432/getchapull
    username: postgres
    password: postgres

application:
  jwt:
    secretKey: mustbesecuremustbesecuremustbesecuremustbesecurekk
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14
