app:
  datasource:
    jdbc-url: jdbc:postgresql://postgres:5432/refactor_postgres
    username: postgres
    password: postgres

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  jwt:
    secretKey: mustbesecuremustbesecuremustbesecuremustbesecurekk
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14
