app:
  datasource:
    jdbc-url: ${JDBC_HOST}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

spring:
  flyway:
    enabled: true
    url: ${JDBC_HOST}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  jwt:
    secretKey: mustbesecuremustbesecuremustbesecuremustbesecurekk
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14
