app:
  datasource:
#    jdbc-url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}

    jdbc-url: jdbc:postgresql://localhost:5432/springmetaldb
    username: postgres
    password: password

    pool-size: 30

application:
  jwt:
    secretKey: mustbesecuremustbesecuremustbesecuremustbesecure
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14

