CREATE TABLE album(
    ALBUM_ID UUID NOT NULL PRIMARY KEY,
    ALBUM_NAME VARCHAR(100) NOT NULL,
    BAND_ID UUID NOT NULL,
    ALBUM_YEAR VARCHAR(10) NOT NULL,
    ALBUM_COVER VARCHAR(200) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL
);