CREATE TABLE user_profile(
    USERNAME VARCHAR(100) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(500) NOT NULL,
    FULLNAME VARCHAR(100) NOT NULL,
    USER_ROLE VARCHAR(50) NOT NULL,
    IS_ACCOUNT_NON_EXPIRED VARCHAR(5) NOT NULL,
    IS_ACCOUNT_NON_LOCKED VARCHAR(5) NOT NULL,
    IS_CREDENTIALS_NON_EXPIRED VARCHAR(5) NOT NULL,
    IS_ENABLED VARCHAR(5) NOT NULL,
    FRIENDS TEXT[],
    FOLLOWERS INTEGER
);