CREATE TABLE review (
    REVIEW_ID UUID NOT NULL PRIMARY KEY,
    REVIEW_TITLE VARCHAR(100) NOT NULL,
    REVIEW_CONTENT VARCHAR(1000) NOT NULL,
    REVIEW_POINT VARCHAR(19) NOT NULL,
    ALBUM_ID UUID NOT NULL,
    USERNAME VARCHAR(100) NOT NULL
)