CREATE TABLE review (
    REVIEW_ID SERIAL PRIMARY KEY,
    REVIEW_TITLE VARCHAR(100) NOT NULL,
    REVIEW_CONTENT VARCHAR(1000) NOT NULL,
    REVIEW_POINT VARCHAR(19) NOT NULL,
    ALBUM_ID UUID NOT NULL,
    ALBUM_NAME VARCHAR(100) NOT NULL,
    BAND_NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    DATE VARCHAR(100) NOT NULL
)